/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-digitizers_39
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DIGITIZERS_39_API_H
#define INCLUDED_DIGITIZERS_39_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_digitizers_39_EXPORTS
#define DIGITIZERS_39_API __GR_ATTR_EXPORT
#else
#define DIGITIZERS_39_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DIGITIZERS_39_API_H */
