/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(picoscope_4000a_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d52135399b397a2bed702af8ac837fdd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include </opt/picoscope/include/libps4000a/ps4000aApi.h>
#include </opt/picoscope/include/libps4000a/PicoStatus.h>
#include <pulsed_power_daq/picoscope_4000a_source.h>
// pydoc.h is automatically generated in the build directory
#include <picoscope_4000a_source_pydoc.h>

void bind_picoscope_4000a_source(py::module& m)
{

    using picoscope_4000a_source    = gr::pulsed_power_daq::picoscope_4000a_source;


    py::class_<picoscope_4000a_source,
        std::shared_ptr<picoscope_4000a_source>>(m, "picoscope_4000a_source", D(picoscope_4000a_source))

        .def(py::init(&picoscope_4000a_source::make),
           py::arg("serial_number"),
           py::arg("auto_arm"),
           D(picoscope_4000a_source,make)
        )
        



        ;




}








