/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(power_calc_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cd45ec5596f4453a9eab3746b37399b6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <digitizers_39/power_calc_ff.h>
// pydoc.h is automatically generated in the build directory
#include <power_calc_ff_pydoc.h>

void bind_power_calc_ff(py::module& m)
{

    using power_calc_ff    = gr::digitizers_39::power_calc_ff;


    py::class_<power_calc_ff,
        std::shared_ptr<power_calc_ff>>(m, "power_calc_ff", D(power_calc_ff))

        .def(py::init(&power_calc_ff::make),
           py::arg("alpha") =  0.0000001,
           D(power_calc_ff,make)
        )
        



        ;




}








